name: SpawnPlugin
version: '2.0.0'
main: me.matt5262.spawnPlugin.SpawnPlugin
api-version: '1.21'
authors: [ Matt_5262 ]
description: My second first plugin ever?
commands:
  setspawn:
    description: Sets the spawn!
    usage: /<command>
    permission: spawnplugin.setspawn
    permission-message: You do not have permission for this command!
  spawn:
    description: Teleport to spawn!
    usage: /<command>
    permission: spawnplugin.spawn
    permission-message: You do not have permission for this command!
  msp:
    description: SpawnPlugin Main Commands.
    usage: /<command>
    permission: spawnplugin.msp
    permission-message: You do not have permission for this command!
permissions:
  spawnplugin.*:
    description: gives all access to my spawn plugin
    children:
      spawnplugin.msp: true
      spawnplugin.repeat: true
      spawnplugin.spawn: true
      spawnplugin.setspawn: true
  spawnplugin.msp:
    description: Allows the spawnplugin command for help and spawn reset!
    default: op
  spawnplugin.repeat:
    description: Allows the repeat command!
    default: true
  spawnplugin.spawn:
    description: Allows spawn command!
    default: true
  spawnplugin.setspawn:
    description: Allows setspawn!
    default: op